---
branches:
  only:
  - master
  - develop
  - /^greenkeeper/.*$/
  - /^feature/.*$/
language: node_js
node_js:
  - stable
  - 10
  - 9
  - 8
env:
  global:
    - CC_TEST_REPORTER_ID=d561d79356a960a82869a05d3d7f941ad652ee4f569b14a1838e5927d3b8a4d9
before_install:
  - '[[ $(node -v) =~ ^v11.*$ ]] || npm install -g npm@latest'
  - npm install -g greenkeeper-lockfile
install: npm install
before_script:
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - greenkeeper-lockfile-upload
  - "[ $TRAVIS_NODE_VERSION = stable ]
  && nyc report --reporter=lcov
  && ./cc-test-reporter after-build --debug -t lcov --exit-code $TRAVIS_TEST_RESULT
  || echo 'Coverage skipped'"
